<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260124173303 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE contexte (id UUID NOT NULL, libelle VARCHAR(255) NOT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_contexte_libelle ON contexte (libelle)');
        $this->addSql('COMMENT ON COLUMN contexte.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN contexte.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE csp (id UUID NOT NULL, libelle VARCHAR(255) NOT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_csp_libelle ON csp (libelle)');
        $this->addSql('COMMENT ON COLUMN csp.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN csp.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE delete_log (id UUID NOT NULL, model_name VARCHAR(255) NOT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN delete_log.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN delete_log.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE evenement (id UUID NOT NULL, start_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, libelle VARCHAR(255) NOT NULL, latitude VARCHAR(32) DEFAULT NULL, longitude VARCHAR(32) DEFAULT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_evenement_libelle ON evenement (libelle)');
        $this->addSql('COMMENT ON COLUMN evenement.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN evenement.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE evenement_exposition (evenement_id UUID NOT NULL, exposition_id UUID NOT NULL, PRIMARY KEY(evenement_id, exposition_id))');
        $this->addSql('CREATE INDEX IDX_4D4B415DFD02F13 ON evenement_exposition (evenement_id)');
        $this->addSql('CREATE INDEX IDX_4D4B415D88ED476F ON evenement_exposition (exposition_id)');
        $this->addSql('COMMENT ON COLUMN evenement_exposition.evenement_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN evenement_exposition.exposition_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE exposition (id UUID NOT NULL, contexte_id UUID DEFAULT NULL, organisateur_editeur_id UUID DEFAULT NULL, organisateur_diffuseur_id UUID DEFAULT NULL, libelle VARCHAR(255) NOT NULL, synopsis TEXT DEFAULT NULL, description TEXT DEFAULT NULL, logo VARCHAR(128) DEFAULT NULL, publics VARCHAR(255) DEFAULT NULL, langues VARCHAR(255) DEFAULT NULL, url_illustration VARCHAR(255) DEFAULT NULL, url_studio VARCHAR(255) DEFAULT NULL, start_at DATE DEFAULT NULL, end_at DATE DEFAULT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BC31FD1399B36A86 ON exposition (contexte_id)');
        $this->addSql('CREATE INDEX IDX_BC31FD1316275ABF ON exposition (organisateur_editeur_id)');
        $this->addSql('CREATE INDEX IDX_BC31FD1351399080 ON exposition (organisateur_diffuseur_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_exposition_libelle ON exposition (libelle)');
        $this->addSql('COMMENT ON COLUMN exposition.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN exposition.contexte_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN exposition.organisateur_editeur_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN exposition.organisateur_diffuseur_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN exposition.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE exposition_visiteurneeds (id UUID NOT NULL, exposition_id UUID NOT NULL, has_genre BOOLEAN DEFAULT false NOT NULL, has_date_naissance BOOLEAN DEFAULT false NOT NULL, has_code_postal BOOLEAN DEFAULT false NOT NULL, has_ville BOOLEAN DEFAULT false NOT NULL, has_adresse BOOLEAN DEFAULT false NOT NULL, has_prenom BOOLEAN DEFAULT false NOT NULL, has_nom BOOLEAN DEFAULT false NOT NULL, has_csp BOOLEAN DEFAULT false NOT NULL, has_num_mobile BOOLEAN DEFAULT false NOT NULL, has_facebook_id BOOLEAN DEFAULT false NOT NULL, has_google_id BOOLEAN DEFAULT false NOT NULL, has_twitter_id BOOLEAN DEFAULT false NOT NULL, has_flickr_id BOOLEAN DEFAULT false NOT NULL, has_dailymotion_id BOOLEAN DEFAULT false NOT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B90578E288ED476F ON exposition_visiteurneeds (exposition_id)');
        $this->addSql('COMMENT ON COLUMN exposition_visiteurneeds.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN exposition_visiteurneeds.exposition_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN exposition_visiteurneeds.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE langue_exposition_visiteurneeds (exposition_visiteurneeds_id UUID NOT NULL, langue_id UUID NOT NULL, PRIMARY KEY(exposition_visiteurneeds_id, langue_id))');
        $this->addSql('CREATE INDEX IDX_FAB180F15BABC636 ON langue_exposition_visiteurneeds (exposition_visiteurneeds_id)');
        $this->addSql('CREATE INDEX IDX_FAB180F12AADBACD ON langue_exposition_visiteurneeds (langue_id)');
        $this->addSql('COMMENT ON COLUMN langue_exposition_visiteurneeds.exposition_visiteurneeds_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN langue_exposition_visiteurneeds.langue_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE preferencemedia_exposition_visiteurneeds (exposition_visiteurneeds_id UUID NOT NULL, preference_media_id UUID NOT NULL, PRIMARY KEY(exposition_visiteurneeds_id, preference_media_id))');
        $this->addSql('CREATE INDEX IDX_37D03C7F5BABC636 ON preferencemedia_exposition_visiteurneeds (exposition_visiteurneeds_id)');
        $this->addSql('CREATE INDEX IDX_37D03C7FF748211E ON preferencemedia_exposition_visiteurneeds (preference_media_id)');
        $this->addSql('COMMENT ON COLUMN preferencemedia_exposition_visiteurneeds.exposition_visiteurneeds_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN preferencemedia_exposition_visiteurneeds.preference_media_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE flotte (id UUID NOT NULL, exposition_id UUID DEFAULT NULL, libelle VARCHAR(255) NOT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_759BD95488ED476F ON flotte (exposition_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_flotte_libelle ON flotte (libelle)');
        $this->addSql('COMMENT ON COLUMN flotte.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN flotte.exposition_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN flotte.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE interactif (id UUID NOT NULL, libelle VARCHAR(255) NOT NULL, source_type VARCHAR(32) DEFAULT NULL, synopsis TEXT DEFAULT NULL, description TEXT DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, categorie VARCHAR(128) DEFAULT NULL, version VARCHAR(32) DEFAULT NULL, editeur VARCHAR(255) DEFAULT NULL, publics VARCHAR(255) DEFAULT NULL, markets VARCHAR(255) DEFAULT NULL, url_market_ios VARCHAR(255) DEFAULT NULL, url_market_android VARCHAR(255) DEFAULT NULL, url_market_windows VARCHAR(255) DEFAULT NULL, langues VARCHAR(255) DEFAULT NULL, image1 VARCHAR(255) DEFAULT NULL, image2 VARCHAR(255) DEFAULT NULL, image3 VARCHAR(255) DEFAULT NULL, date_diff DATE DEFAULT NULL, explications_resultats TEXT DEFAULT NULL, score TEXT DEFAULT NULL, variable TEXT DEFAULT NULL, url_scheme VARCHAR(128) DEFAULT NULL, url_fichier_interactif VARCHAR(255) DEFAULT NULL, url_pierre_de_rosette VARCHAR(255) DEFAULT NULL, url_illustration VARCHAR(255) DEFAULT NULL, url_interactif_type INT DEFAULT NULL, url_interactif_choice VARCHAR(255) DEFAULT NULL, url_visiteur_type INT DEFAULT NULL, url_start_at INT DEFAULT NULL, url_start_at_type VARCHAR(255) DEFAULT NULL, url_end_at INT DEFAULT NULL, url_end_at_type VARCHAR(255) DEFAULT NULL, refresh_deploiement BOOLEAN DEFAULT false NOT NULL, is_visiteur_needed BOOLEAN DEFAULT false NOT NULL, is_logvisite_needed BOOLEAN DEFAULT false NOT NULL, is_logvisite_verbose_needed BOOLEAN DEFAULT false NOT NULL, is_parcours_needed BOOLEAN DEFAULT false NOT NULL, ordre INT DEFAULT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_interactif_libelle ON interactif (libelle)');
        $this->addSql('COMMENT ON COLUMN interactif.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN interactif.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE langue (id UUID NOT NULL, libelle VARCHAR(128) NOT NULL, short_libelle VARCHAR(10) NOT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_langue_libelle ON langue (libelle)');
        $this->addSql('COMMENT ON COLUMN langue.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN langue.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE log_visite (id UUID NOT NULL, interactif_id UUID DEFAULT NULL, visite_id UUID DEFAULT NULL, visiteur_id UUID DEFAULT NULL, exposition_id UUID DEFAULT NULL, interactif_libelle VARCHAR(255) DEFAULT NULL, connection VARCHAR(64) DEFAULT NULL, start_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, resultats TEXT DEFAULT NULL, score INT DEFAULT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A566DF19C5D2347F ON log_visite (interactif_id)');
        $this->addSql('CREATE INDEX IDX_A566DF19C1C5DC59 ON log_visite (visite_id)');
        $this->addSql('CREATE INDEX IDX_A566DF197F72333D ON log_visite (visiteur_id)');
        $this->addSql('CREATE INDEX IDX_A566DF1988ED476F ON log_visite (exposition_id)');
        $this->addSql('COMMENT ON COLUMN log_visite.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN log_visite.interactif_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN log_visite.visite_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN log_visite.visiteur_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN log_visite.exposition_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN log_visite.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE medaille (id UUID NOT NULL, medaille_type_id UUID DEFAULT NULL, exposition_id UUID DEFAULT NULL, interactif_id UUID DEFAULT NULL, libelle VARCHAR(255) NOT NULL, image VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, condition_obtention TEXT DEFAULT NULL, is_unique BOOLEAN DEFAULT true NOT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_33062141D21BCFE ON medaille (medaille_type_id)');
        $this->addSql('CREATE INDEX IDX_3306214188ED476F ON medaille (exposition_id)');
        $this->addSql('CREATE INDEX IDX_33062141C5D2347F ON medaille (interactif_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_medaille_libelle ON medaille (libelle)');
        $this->addSql('COMMENT ON COLUMN medaille.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN medaille.medaille_type_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN medaille.exposition_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN medaille.interactif_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN medaille.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE medaille_type (id UUID NOT NULL, libelle VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN medaille_type.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN medaille_type.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE notification (id UUID NOT NULL, visiteur_id UUID NOT NULL, visite_id UUID NOT NULL, libelle VARCHAR(255) DEFAULT NULL, from_model VARCHAR(255) DEFAULT NULL, from_model_id VARCHAR(255) DEFAULT NULL, parameter VARCHAR(255) DEFAULT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BF5476CA7F72333D ON notification (visiteur_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CAC1C5DC59 ON notification (visite_id)');
        $this->addSql('COMMENT ON COLUMN notification.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notification.visiteur_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notification.visite_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notification.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE organisateur (id UUID NOT NULL, libelle VARCHAR(255) NOT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_organisateur_libelle ON organisateur (libelle)');
        $this->addSql('COMMENT ON COLUMN organisateur.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN organisateur.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE parcours (id UUID NOT NULL, libelle VARCHAR(255) NOT NULL, ordre INT DEFAULT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_parcours_libelle ON parcours (libelle)');
        $this->addSql('COMMENT ON COLUMN parcours.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN parcours.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE exposition_parcours (parcours_id UUID NOT NULL, exposition_id UUID NOT NULL, PRIMARY KEY(parcours_id, exposition_id))');
        $this->addSql('CREATE INDEX IDX_254E99446E38C0DB ON exposition_parcours (parcours_id)');
        $this->addSql('CREATE INDEX IDX_254E994488ED476F ON exposition_parcours (exposition_id)');
        $this->addSql('COMMENT ON COLUMN exposition_parcours.parcours_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN exposition_parcours.exposition_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE parcours_interactif (parcours_id UUID NOT NULL, interactif_id UUID NOT NULL, PRIMARY KEY(parcours_id, interactif_id))');
        $this->addSql('CREATE INDEX IDX_D0E46E276E38C0DB ON parcours_interactif (parcours_id)');
        $this->addSql('CREATE INDEX IDX_D0E46E27C5D2347F ON parcours_interactif (interactif_id)');
        $this->addSql('COMMENT ON COLUMN parcours_interactif.parcours_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN parcours_interactif.interactif_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE peripherique (id UUID NOT NULL, flotte_id UUID DEFAULT NULL, interactif_id UUID NOT NULL, adresse_mac VARCHAR(64) NOT NULL, adresse_ip VARCHAR(32) DEFAULT NULL, serial_number VARCHAR(255) DEFAULT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CFCF03653AD377B3 ON peripherique (flotte_id)');
        $this->addSql('CREATE INDEX IDX_CFCF0365C5D2347F ON peripherique (interactif_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_peripherique_adresse_mac ON peripherique (adresse_mac)');
        $this->addSql('COMMENT ON COLUMN peripherique.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN peripherique.flotte_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN peripherique.interactif_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN peripherique.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE preferencemedia (id UUID NOT NULL, libelle VARCHAR(255) NOT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_preferencemedia_libelle ON preferencemedia (libelle)');
        $this->addSql('COMMENT ON COLUMN preferencemedia.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN preferencemedia.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE rfid (id UUID NOT NULL, groupe_id UUID DEFAULT NULL, type VARCHAR(64) DEFAULT NULL, valeur1 VARCHAR(255) DEFAULT \'\' NOT NULL, valeur2 VARCHAR(255) DEFAULT \'\' NOT NULL, valeur3 VARCHAR(255) DEFAULT \'\' NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, is_resettable BOOLEAN DEFAULT true NOT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_52C875367A45358C ON rfid (groupe_id)');
        $this->addSql('CREATE INDEX idx_rfid_is_resettable ON rfid (is_resettable)');
        $this->addSql('COMMENT ON COLUMN rfid.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN rfid.groupe_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN rfid.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE rfid_groupe (id UUID NOT NULL, nom VARCHAR(255) NOT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_rfid_groupe_nom ON rfid_groupe (nom)');
        $this->addSql('COMMENT ON COLUMN rfid_groupe.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN rfid_groupe.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE rfid_groupe_visiteur (id UUID NOT NULL, rfid_groupe_id UUID NOT NULL, langue_id UUID NOT NULL, csp_id UUID DEFAULT NULL, nom VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, genre VARCHAR(10) DEFAULT NULL, age INT DEFAULT NULL, code_postal INT DEFAULT NULL, commentaire TEXT DEFAULT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_ADCBA71BF5094468 ON rfid_groupe_visiteur (rfid_groupe_id)');
        $this->addSql('CREATE INDEX IDX_ADCBA71B2AADBACD ON rfid_groupe_visiteur (langue_id)');
        $this->addSql('CREATE INDEX IDX_ADCBA71B73EFFAF6 ON rfid_groupe_visiteur (csp_id)');
        $this->addSql('COMMENT ON COLUMN rfid_groupe_visiteur.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN rfid_groupe_visiteur.rfid_groupe_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN rfid_groupe_visiteur.langue_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN rfid_groupe_visiteur.csp_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN rfid_groupe_visiteur.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE rulerz (id UUID NOT NULL, libelle VARCHAR(255) DEFAULT NULL, action TEXT DEFAULT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN rulerz.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN rulerz.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE rulerz_execution (id UUID NOT NULL, rulerz_id UUID NOT NULL, event VARCHAR(255) DEFAULT NULL, entity_uid VARCHAR(255) DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, execution_data TEXT DEFAULT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4C18C50CD6533704 ON rulerz_execution (rulerz_id)');
        $this->addSql('COMMENT ON COLUMN rulerz_execution.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN rulerz_execution.rulerz_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN rulerz_execution.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE rulerz_listenner (id UUID NOT NULL, rulerz_id UUID NOT NULL, event VARCHAR(255) DEFAULT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FE925B0CD6533704 ON rulerz_listenner (rulerz_id)');
        $this->addSql('COMMENT ON COLUMN rulerz_listenner.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN rulerz_listenner.rulerz_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN rulerz_listenner.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE sent_message (id UUID NOT NULL, mail_from VARCHAR(255) NOT NULL, mail_to VARCHAR(255) NOT NULL, subject VARCHAR(255) NOT NULL, content TEXT DEFAULT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN sent_message.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN sent_message.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE sync_log (id UUID NOT NULL, from_datetime_sync TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, to_datetime_sync TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, origin VARCHAR(255) DEFAULT NULL, is_done BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN sync_log.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN sync_log.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE template_mail (id UUID NOT NULL, libelle VARCHAR(255) NOT NULL, contenu TEXT DEFAULT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_templatemail_libelle ON template_mail (libelle)');
        $this->addSql('COMMENT ON COLUMN template_mail.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN template_mail.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE typologie (id UUID NOT NULL, libelle VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_typologie_libelle ON typologie (libelle)');
        $this->addSql('COMMENT ON COLUMN typologie.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN typologie.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE visite (id UUID NOT NULL, visiteur_id UUID DEFAULT NULL, navinum_id UUID DEFAULT NULL, groupe_id UUID DEFAULT NULL, exposition_id UUID DEFAULT NULL, parcours_id UUID DEFAULT NULL, interactif_id UUID DEFAULT NULL, exposition_libelle VARCHAR(255) DEFAULT NULL, parcours_libelle VARCHAR(255) DEFAULT NULL, connexion_id VARCHAR(255) DEFAULT NULL, is_ending BOOLEAN DEFAULT false NOT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B09C8CBB7F72333D ON visite (visiteur_id)');
        $this->addSql('CREATE INDEX IDX_B09C8CBB402D6A1A ON visite (navinum_id)');
        $this->addSql('CREATE INDEX IDX_B09C8CBB7A45358C ON visite (groupe_id)');
        $this->addSql('CREATE INDEX IDX_B09C8CBB88ED476F ON visite (exposition_id)');
        $this->addSql('CREATE INDEX IDX_B09C8CBB6E38C0DB ON visite (parcours_id)');
        $this->addSql('CREATE INDEX IDX_B09C8CBBC5D2347F ON visite (interactif_id)');
        $this->addSql('CREATE INDEX idx_visite_connexion ON visite (connexion_id)');
        $this->addSql('COMMENT ON COLUMN visite.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN visite.visiteur_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN visite.navinum_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN visite.groupe_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN visite.exposition_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN visite.parcours_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN visite.interactif_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN visite.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE visiteur (id UUID NOT NULL, contexte_creation_id UUID DEFAULT NULL, langue_id UUID DEFAULT NULL, csp_id UUID DEFAULT NULL, password_son VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, type VARCHAR(32) NOT NULL, has_photo BOOLEAN DEFAULT false NOT NULL, genre VARCHAR(10) DEFAULT NULL, date_naissance DATE DEFAULT NULL, adresse VARCHAR(255) DEFAULT NULL, code_postal VARCHAR(10) DEFAULT NULL, ville VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, pseudo_son VARCHAR(255) DEFAULT NULL, has_newsletter BOOLEAN DEFAULT NULL, url_avatar VARCHAR(255) DEFAULT NULL, num_mobile VARCHAR(64) DEFAULT NULL, facebook_id VARCHAR(255) DEFAULT NULL, google_id VARCHAR(255) DEFAULT NULL, twitter_id VARCHAR(255) DEFAULT NULL, flickr_id VARCHAR(255) DEFAULT NULL, dailymotion_id VARCHAR(255) DEFAULT NULL, is_anonyme BOOLEAN DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4EA587B83574D86F ON visiteur (contexte_creation_id)');
        $this->addSql('CREATE INDEX IDX_4EA587B82AADBACD ON visiteur (langue_id)');
        $this->addSql('CREATE INDEX IDX_4EA587B873EFFAF6 ON visiteur (csp_id)');
        $this->addSql('CREATE INDEX idx_visiteur_email ON visiteur (email)');
        $this->addSql('CREATE INDEX idx_visiteur_password_son ON visiteur (password_son)');
        $this->addSql('CREATE INDEX idx_visiteur_pseudo_son ON visiteur (pseudo_son)');
        $this->addSql('COMMENT ON COLUMN visiteur.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN visiteur.contexte_creation_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN visiteur.langue_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN visiteur.csp_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN visiteur.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE preferencemedia_visiteur (visiteur_id UUID NOT NULL, preference_media_id UUID NOT NULL, PRIMARY KEY(visiteur_id, preference_media_id))');
        $this->addSql('CREATE INDEX IDX_BB6C49CE7F72333D ON preferencemedia_visiteur (visiteur_id)');
        $this->addSql('CREATE INDEX IDX_BB6C49CEF748211E ON preferencemedia_visiteur (preference_media_id)');
        $this->addSql('COMMENT ON COLUMN preferencemedia_visiteur.visiteur_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN preferencemedia_visiteur.preference_media_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE visiteur_medaille (id UUID NOT NULL, visiteur_id UUID NOT NULL, medaille_id UUID NOT NULL, connection VARCHAR(255) DEFAULT \'\' NOT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_97451DB27F72333D ON visiteur_medaille (visiteur_id)');
        $this->addSql('CREATE INDEX IDX_97451DB272E59222 ON visiteur_medaille (medaille_id)');
        $this->addSql('COMMENT ON COLUMN visiteur_medaille.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN visiteur_medaille.visiteur_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN visiteur_medaille.medaille_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN visiteur_medaille.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE xp (id UUID NOT NULL, visiteur_id UUID NOT NULL, typologie_id UUID NOT NULL, score INT NOT NULL, is_tosync BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F63A903D7F72333D ON xp (visiteur_id)');
        $this->addSql('CREATE INDEX IDX_F63A903D42F4634A ON xp (typologie_id)');
        $this->addSql('COMMENT ON COLUMN xp.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN xp.visiteur_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN xp.typologie_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN xp.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE messenger_messages (id BIGSERIAL NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE OR REPLACE FUNCTION notify_messenger_messages() RETURNS TRIGGER AS $$
            BEGIN
                PERFORM pg_notify(\'messenger_messages\', NEW.queue_name::text);
                RETURN NEW;
            END;
        $$ LANGUAGE plpgsql;');
        $this->addSql('DROP TRIGGER IF EXISTS notify_trigger ON messenger_messages;');
        $this->addSql('CREATE TRIGGER notify_trigger AFTER INSERT OR UPDATE ON messenger_messages FOR EACH ROW EXECUTE PROCEDURE notify_messenger_messages();');
        $this->addSql('ALTER TABLE evenement_exposition ADD CONSTRAINT FK_4D4B415DFD02F13 FOREIGN KEY (evenement_id) REFERENCES evenement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE evenement_exposition ADD CONSTRAINT FK_4D4B415D88ED476F FOREIGN KEY (exposition_id) REFERENCES exposition (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exposition ADD CONSTRAINT FK_BC31FD1399B36A86 FOREIGN KEY (contexte_id) REFERENCES contexte (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exposition ADD CONSTRAINT FK_BC31FD1316275ABF FOREIGN KEY (organisateur_editeur_id) REFERENCES organisateur (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exposition ADD CONSTRAINT FK_BC31FD1351399080 FOREIGN KEY (organisateur_diffuseur_id) REFERENCES organisateur (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exposition_visiteurneeds ADD CONSTRAINT FK_B90578E288ED476F FOREIGN KEY (exposition_id) REFERENCES exposition (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE langue_exposition_visiteurneeds ADD CONSTRAINT FK_FAB180F15BABC636 FOREIGN KEY (exposition_visiteurneeds_id) REFERENCES exposition_visiteurneeds (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE langue_exposition_visiteurneeds ADD CONSTRAINT FK_FAB180F12AADBACD FOREIGN KEY (langue_id) REFERENCES langue (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE preferencemedia_exposition_visiteurneeds ADD CONSTRAINT FK_37D03C7F5BABC636 FOREIGN KEY (exposition_visiteurneeds_id) REFERENCES exposition_visiteurneeds (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE preferencemedia_exposition_visiteurneeds ADD CONSTRAINT FK_37D03C7FF748211E FOREIGN KEY (preference_media_id) REFERENCES preferencemedia (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flotte ADD CONSTRAINT FK_759BD95488ED476F FOREIGN KEY (exposition_id) REFERENCES exposition (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE log_visite ADD CONSTRAINT FK_A566DF19C5D2347F FOREIGN KEY (interactif_id) REFERENCES interactif (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE log_visite ADD CONSTRAINT FK_A566DF19C1C5DC59 FOREIGN KEY (visite_id) REFERENCES visite (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE log_visite ADD CONSTRAINT FK_A566DF197F72333D FOREIGN KEY (visiteur_id) REFERENCES visiteur (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE log_visite ADD CONSTRAINT FK_A566DF1988ED476F FOREIGN KEY (exposition_id) REFERENCES exposition (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medaille ADD CONSTRAINT FK_33062141D21BCFE FOREIGN KEY (medaille_type_id) REFERENCES medaille_type (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medaille ADD CONSTRAINT FK_3306214188ED476F FOREIGN KEY (exposition_id) REFERENCES exposition (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medaille ADD CONSTRAINT FK_33062141C5D2347F FOREIGN KEY (interactif_id) REFERENCES interactif (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA7F72333D FOREIGN KEY (visiteur_id) REFERENCES visiteur (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAC1C5DC59 FOREIGN KEY (visite_id) REFERENCES visite (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exposition_parcours ADD CONSTRAINT FK_254E99446E38C0DB FOREIGN KEY (parcours_id) REFERENCES parcours (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exposition_parcours ADD CONSTRAINT FK_254E994488ED476F FOREIGN KEY (exposition_id) REFERENCES exposition (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parcours_interactif ADD CONSTRAINT FK_D0E46E276E38C0DB FOREIGN KEY (parcours_id) REFERENCES parcours (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parcours_interactif ADD CONSTRAINT FK_D0E46E27C5D2347F FOREIGN KEY (interactif_id) REFERENCES interactif (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE peripherique ADD CONSTRAINT FK_CFCF03653AD377B3 FOREIGN KEY (flotte_id) REFERENCES flotte (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE peripherique ADD CONSTRAINT FK_CFCF0365C5D2347F FOREIGN KEY (interactif_id) REFERENCES interactif (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rfid ADD CONSTRAINT FK_52C875367A45358C FOREIGN KEY (groupe_id) REFERENCES rfid_groupe (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rfid_groupe_visiteur ADD CONSTRAINT FK_ADCBA71BF5094468 FOREIGN KEY (rfid_groupe_id) REFERENCES rfid_groupe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rfid_groupe_visiteur ADD CONSTRAINT FK_ADCBA71B2AADBACD FOREIGN KEY (langue_id) REFERENCES langue (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rfid_groupe_visiteur ADD CONSTRAINT FK_ADCBA71B73EFFAF6 FOREIGN KEY (csp_id) REFERENCES csp (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rulerz_execution ADD CONSTRAINT FK_4C18C50CD6533704 FOREIGN KEY (rulerz_id) REFERENCES rulerz (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rulerz_listenner ADD CONSTRAINT FK_FE925B0CD6533704 FOREIGN KEY (rulerz_id) REFERENCES rulerz (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visite ADD CONSTRAINT FK_B09C8CBB7F72333D FOREIGN KEY (visiteur_id) REFERENCES visiteur (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visite ADD CONSTRAINT FK_B09C8CBB402D6A1A FOREIGN KEY (navinum_id) REFERENCES rfid (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visite ADD CONSTRAINT FK_B09C8CBB7A45358C FOREIGN KEY (groupe_id) REFERENCES rfid_groupe_visiteur (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visite ADD CONSTRAINT FK_B09C8CBB88ED476F FOREIGN KEY (exposition_id) REFERENCES exposition (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visite ADD CONSTRAINT FK_B09C8CBB6E38C0DB FOREIGN KEY (parcours_id) REFERENCES parcours (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visite ADD CONSTRAINT FK_B09C8CBBC5D2347F FOREIGN KEY (interactif_id) REFERENCES interactif (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visiteur ADD CONSTRAINT FK_4EA587B83574D86F FOREIGN KEY (contexte_creation_id) REFERENCES contexte (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visiteur ADD CONSTRAINT FK_4EA587B82AADBACD FOREIGN KEY (langue_id) REFERENCES langue (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visiteur ADD CONSTRAINT FK_4EA587B873EFFAF6 FOREIGN KEY (csp_id) REFERENCES csp (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE preferencemedia_visiteur ADD CONSTRAINT FK_BB6C49CE7F72333D FOREIGN KEY (visiteur_id) REFERENCES visiteur (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE preferencemedia_visiteur ADD CONSTRAINT FK_BB6C49CEF748211E FOREIGN KEY (preference_media_id) REFERENCES preferencemedia (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visiteur_medaille ADD CONSTRAINT FK_97451DB27F72333D FOREIGN KEY (visiteur_id) REFERENCES visiteur (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visiteur_medaille ADD CONSTRAINT FK_97451DB272E59222 FOREIGN KEY (medaille_id) REFERENCES medaille (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE xp ADD CONSTRAINT FK_F63A903D7F72333D FOREIGN KEY (visiteur_id) REFERENCES visiteur (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE xp ADD CONSTRAINT FK_F63A903D42F4634A FOREIGN KEY (typologie_id) REFERENCES typologie (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE evenement_exposition DROP CONSTRAINT FK_4D4B415DFD02F13');
        $this->addSql('ALTER TABLE evenement_exposition DROP CONSTRAINT FK_4D4B415D88ED476F');
        $this->addSql('ALTER TABLE exposition DROP CONSTRAINT FK_BC31FD1399B36A86');
        $this->addSql('ALTER TABLE exposition DROP CONSTRAINT FK_BC31FD1316275ABF');
        $this->addSql('ALTER TABLE exposition DROP CONSTRAINT FK_BC31FD1351399080');
        $this->addSql('ALTER TABLE exposition_visiteurneeds DROP CONSTRAINT FK_B90578E288ED476F');
        $this->addSql('ALTER TABLE langue_exposition_visiteurneeds DROP CONSTRAINT FK_FAB180F15BABC636');
        $this->addSql('ALTER TABLE langue_exposition_visiteurneeds DROP CONSTRAINT FK_FAB180F12AADBACD');
        $this->addSql('ALTER TABLE preferencemedia_exposition_visiteurneeds DROP CONSTRAINT FK_37D03C7F5BABC636');
        $this->addSql('ALTER TABLE preferencemedia_exposition_visiteurneeds DROP CONSTRAINT FK_37D03C7FF748211E');
        $this->addSql('ALTER TABLE flotte DROP CONSTRAINT FK_759BD95488ED476F');
        $this->addSql('ALTER TABLE log_visite DROP CONSTRAINT FK_A566DF19C5D2347F');
        $this->addSql('ALTER TABLE log_visite DROP CONSTRAINT FK_A566DF19C1C5DC59');
        $this->addSql('ALTER TABLE log_visite DROP CONSTRAINT FK_A566DF197F72333D');
        $this->addSql('ALTER TABLE log_visite DROP CONSTRAINT FK_A566DF1988ED476F');
        $this->addSql('ALTER TABLE medaille DROP CONSTRAINT FK_33062141D21BCFE');
        $this->addSql('ALTER TABLE medaille DROP CONSTRAINT FK_3306214188ED476F');
        $this->addSql('ALTER TABLE medaille DROP CONSTRAINT FK_33062141C5D2347F');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA7F72333D');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAC1C5DC59');
        $this->addSql('ALTER TABLE exposition_parcours DROP CONSTRAINT FK_254E99446E38C0DB');
        $this->addSql('ALTER TABLE exposition_parcours DROP CONSTRAINT FK_254E994488ED476F');
        $this->addSql('ALTER TABLE parcours_interactif DROP CONSTRAINT FK_D0E46E276E38C0DB');
        $this->addSql('ALTER TABLE parcours_interactif DROP CONSTRAINT FK_D0E46E27C5D2347F');
        $this->addSql('ALTER TABLE peripherique DROP CONSTRAINT FK_CFCF03653AD377B3');
        $this->addSql('ALTER TABLE peripherique DROP CONSTRAINT FK_CFCF0365C5D2347F');
        $this->addSql('ALTER TABLE rfid DROP CONSTRAINT FK_52C875367A45358C');
        $this->addSql('ALTER TABLE rfid_groupe_visiteur DROP CONSTRAINT FK_ADCBA71BF5094468');
        $this->addSql('ALTER TABLE rfid_groupe_visiteur DROP CONSTRAINT FK_ADCBA71B2AADBACD');
        $this->addSql('ALTER TABLE rfid_groupe_visiteur DROP CONSTRAINT FK_ADCBA71B73EFFAF6');
        $this->addSql('ALTER TABLE rulerz_execution DROP CONSTRAINT FK_4C18C50CD6533704');
        $this->addSql('ALTER TABLE rulerz_listenner DROP CONSTRAINT FK_FE925B0CD6533704');
        $this->addSql('ALTER TABLE visite DROP CONSTRAINT FK_B09C8CBB7F72333D');
        $this->addSql('ALTER TABLE visite DROP CONSTRAINT FK_B09C8CBB402D6A1A');
        $this->addSql('ALTER TABLE visite DROP CONSTRAINT FK_B09C8CBB7A45358C');
        $this->addSql('ALTER TABLE visite DROP CONSTRAINT FK_B09C8CBB88ED476F');
        $this->addSql('ALTER TABLE visite DROP CONSTRAINT FK_B09C8CBB6E38C0DB');
        $this->addSql('ALTER TABLE visite DROP CONSTRAINT FK_B09C8CBBC5D2347F');
        $this->addSql('ALTER TABLE visiteur DROP CONSTRAINT FK_4EA587B83574D86F');
        $this->addSql('ALTER TABLE visiteur DROP CONSTRAINT FK_4EA587B82AADBACD');
        $this->addSql('ALTER TABLE visiteur DROP CONSTRAINT FK_4EA587B873EFFAF6');
        $this->addSql('ALTER TABLE preferencemedia_visiteur DROP CONSTRAINT FK_BB6C49CE7F72333D');
        $this->addSql('ALTER TABLE preferencemedia_visiteur DROP CONSTRAINT FK_BB6C49CEF748211E');
        $this->addSql('ALTER TABLE visiteur_medaille DROP CONSTRAINT FK_97451DB27F72333D');
        $this->addSql('ALTER TABLE visiteur_medaille DROP CONSTRAINT FK_97451DB272E59222');
        $this->addSql('ALTER TABLE xp DROP CONSTRAINT FK_F63A903D7F72333D');
        $this->addSql('ALTER TABLE xp DROP CONSTRAINT FK_F63A903D42F4634A');
        $this->addSql('DROP TABLE contexte');
        $this->addSql('DROP TABLE csp');
        $this->addSql('DROP TABLE delete_log');
        $this->addSql('DROP TABLE evenement');
        $this->addSql('DROP TABLE evenement_exposition');
        $this->addSql('DROP TABLE exposition');
        $this->addSql('DROP TABLE exposition_visiteurneeds');
        $this->addSql('DROP TABLE langue_exposition_visiteurneeds');
        $this->addSql('DROP TABLE preferencemedia_exposition_visiteurneeds');
        $this->addSql('DROP TABLE flotte');
        $this->addSql('DROP TABLE interactif');
        $this->addSql('DROP TABLE langue');
        $this->addSql('DROP TABLE log_visite');
        $this->addSql('DROP TABLE medaille');
        $this->addSql('DROP TABLE medaille_type');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE organisateur');
        $this->addSql('DROP TABLE parcours');
        $this->addSql('DROP TABLE exposition_parcours');
        $this->addSql('DROP TABLE parcours_interactif');
        $this->addSql('DROP TABLE peripherique');
        $this->addSql('DROP TABLE preferencemedia');
        $this->addSql('DROP TABLE rfid');
        $this->addSql('DROP TABLE rfid_groupe');
        $this->addSql('DROP TABLE rfid_groupe_visiteur');
        $this->addSql('DROP TABLE rulerz');
        $this->addSql('DROP TABLE rulerz_execution');
        $this->addSql('DROP TABLE rulerz_listenner');
        $this->addSql('DROP TABLE sent_message');
        $this->addSql('DROP TABLE sync_log');
        $this->addSql('DROP TABLE template_mail');
        $this->addSql('DROP TABLE typologie');
        $this->addSql('DROP TABLE visite');
        $this->addSql('DROP TABLE visiteur');
        $this->addSql('DROP TABLE preferencemedia_visiteur');
        $this->addSql('DROP TABLE visiteur_medaille');
        $this->addSql('DROP TABLE xp');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
